/**
 * #14 try catchについて
 */

// const text1 = "あなたの名前は" + myname + "ですね。" // エラーのあるコード

// console.log("よくできました！")

// try {
//   const text2 = "あなたの名前は" + myname + "ですね。"
// } catch (error) {
//   console.log(error)
// }

// console.log("よくできました！")

/* throwについて */

// try {
//   const myname = "nob"
//   const text3 = "あなたの名前は" + myname + "ですね。"
//   // 強制でエラーを吐き出す
//   throw new Error("「ぐははははは,エラーにしてやる！」") //エラーを作成
// } catch (error) {
//   console.log(error)
//   // console.error(error)
// }

// console.log("よくできました！")
